#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef AGENUI_SWIFT_H
#define AGENUI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AGenUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
SWIFT_CLASS("_TtC6AGenUI11AGenUIError")
@interface AGenUIError : NSObject
/// Whether the operation succeeded
@property (nonatomic, readonly) BOOL result;
/// Error message
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithResult:(BOOL)result message:(NSString * _Nonnull)message OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Component;
@protocol ImageLoader;
@class NSURL;
@protocol Function;
@protocol LoggerDelegate;
enum Level : NSInteger;
/// AGenUI SDK global entry point
/// Singleton responsible for global registration of theme, DesignToken, day/night mode, skills, components, and image loaders.
SWIFT_CLASS_NAMED("AGenUISDK")
@interface AGenUISDK : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Register default theme configuration
/// Registers theme and design token configurations to customize UI component appearance.
/// \param theme Theme configuration JSON string
///
/// \param designToken Design token configuration JSON string
///
///
/// returns:
/// AGenUIError with result and message fields
+ (AGenUIError * _Nonnull)registerDefaultTheme:(NSString * _Nonnull)theme designToken:(NSString * _Nonnull)designToken SWIFT_WARN_UNUSED_RESULT;
/// Set day/night mode
/// \param mode “light” or “dark”
///
+ (void)setDayNightMode:(NSString * _Nonnull)mode;
/// Set whether the host app is a debug build so the SDK can adjust its internal behavior
/// Should be called right after initialize(). Defaults to false if never called.
/// \param isDebug true for debug builds, false for release
///
+ (void)setDebug:(BOOL)isDebug;
/// Get whether the host app is a debug build, previously set via setDebug
///
/// returns:
/// true for debug builds. Returns false if never set.
+ (BOOL)isDebug SWIFT_WARN_UNUSED_RESULT;
/// Set path configuration
/// \param configJson Path configuration JSON string, e.g. {“templateDir”: “/path/to/templates”}
///
///
/// returns:
/// AGenUIError with result and message fields
+ (AGenUIError * _Nonnull)setPathConfig:(NSString * _Nonnull)configJson SWIFT_WARN_UNUSED_RESULT;
/// Apply runtime configuration switches from the host (cloud control)
/// Call once at SDK initialization, before surfaces render. The value is
/// fixed for the session; runtime changes are not supported.
/// \param configJson Runtime config JSON string, e.g. {“borderPixelAlignment”: true}
///
///
/// returns:
/// AGenUIError with result and message fields
+ (AGenUIError * _Nonnull)setRuntimeConfig:(NSString * _Nonnull)configJson SWIFT_WARN_UNUSED_RESULT;
/// Register a custom component factory (Objective-C compatible)
/// note:
/// Overwrites if the component type already exists
/// \param type Component type name
///
/// \param creator Factory closure to create the component, returns a Component instance
///
+ (void)registerComponent:(NSString * _Nonnull)type creator:(Component * _Nonnull (^ _Nonnull)(NSString * _Nonnull, NSDictionary<NSString *, id> * _Nonnull))creator;
/// Register a custom component factory with explicit class name (Objective-C compatible)
/// When called from ObjC, Swift generic T is erased to Component.
/// This method accepts an explicit class name string to resolve the actual
/// Component subclass for correct measurement dispatch.
/// note:
/// Overwrites if the component type already exists
/// \param type Component type name
///
/// \param componentClassName Fully qualified class name string for the Component subclass
///
/// \param creator Factory closure to create the component
///
+ (void)registerComponent:(NSString * _Nonnull)type componentClassName:(NSString * _Nonnull)componentClassName creator:(Component * _Nonnull (^ _Nonnull)(NSString * _Nonnull, NSDictionary<NSString *, id> * _Nonnull))creator;
+ (void)unRegisterComponent:(NSString * _Nonnull)type;
/// Declare a component property as a container of dynamic values
/// By default a property value is parsed but not descended into, so a nested object
/// or array is stored verbatim and any <code>{"path":...}</code> binding or <code>{"call":...}</code>
/// function call inside it never resolves. Registering the property makes the engine
/// walk its whole subtree, resolving nested dynamic values at any depth — including
/// bindings inside a function call’s arguments, and relative paths inside a List
/// item template.
/// Example — AmapText carries its rich-text runs in a <code>spans</code> array:
/// <code>AGenUI.registerDeepParseProperty("AmapText", propertyName: "spans")</code>
/// Must be called before the first render; a declaration made later has no effect on
/// components that have already been parsed.
/// \param componentType Component type, i.e. the JSON <code>component</code> field
///
/// \param propertyName Property name
///
///
/// returns:
/// true on success, false when either name is empty
+ (BOOL)registerDeepParseProperty:(NSString * _Nonnull)componentType propertyName:(NSString * _Nonnull)propertyName;
/// Register a global image loader
/// \param loader A loader instance implementing the ImageLoader protocol
///
+ (void)registerImageLoader:(id <ImageLoader> _Nonnull)loader;
/// Register a custom font from a file URL.
/// The font is loaded via <code>CTFontManager</code> and becomes available for
/// <code>font-family</code> CSS property resolution in all text components.
/// \param familyName the name authors use in <code>font-family</code> (case-insensitive)
///
/// \param fileURL URL pointing to a <code>.ttf</code> or <code>.otf</code> font file
///
///
/// returns:
/// <code>true</code> if registration succeeds
+ (BOOL)registerFont:(NSString * _Nonnull)familyName fileURL:(NSURL * _Nonnull)fileURL SWIFT_WARN_UNUSED_RESULT;
/// Register a font name already available in the system.
/// Use this when the font is declared in <code>Info.plist</code> under <code>UIAppFonts</code>
/// and you want to expose it under a custom CSS family name.
/// \param familyName the name authors use in <code>font-family</code> (case-insensitive)
///
/// \param fontName the actual font name (PostScript name or family name)
///
///
/// returns:
/// <code>true</code> on success
+ (BOOL)registerFont:(NSString * _Nonnull)familyName fontName:(NSString * _Nonnull)fontName SWIFT_WARN_UNUSED_RESULT;
/// Register a platform function with the engine
/// \param function Object implementing the AGenUIFunctionProtocol
///
+ (void)registerFunction:(id <Function> _Nonnull)function;
/// Unregister a previously registered platform function
/// \param name Function name to unregister
///
+ (void)unregisterFunctionWithName:(NSString * _Nonnull)name;
/// Custom Logger
/// note:
/// By setting the delegate, other modules like can receive log output
/// \param customLogger Custom Logger
///
+ (void)setCustomLogger:(id <LoggerDelegate> _Nullable)customLogger;
/// Set the minimum log level for AGenUI SDK.
/// Only logs with level >= the specified level will be output.
/// This controls both the Swift-side filtering and the C++ hot-path
/// early-exit (via <code>IRuntimeLogger.getMinLevel()</code>), so filtered-out
/// messages skip variadic formatting and cross-language bridging entirely.
/// \param level The minimum log level to output.
/// Possible values: <code>.debug</code>(0), <code>.info</code>(1), <code>.warning</code>(2), <code>.error</code>(3), <code>.fatal</code>(4), <code>.performance</code>(5)
///
+ (void)setMinLogLevel:(enum Level)level;
/// Get the current minimum log level for AGenUI SDK.
///
/// returns:
/// The current minimum log level.
+ (enum Level)getMinLogLevel SWIFT_WARN_UNUSED_RESULT;
/// Get the AGenUI SDK version
///
/// returns:
/// Version string
+ (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
@end

@class NSCoder;
/// Component base class - inherits from UIView
/// Core design philosophy: Component is View, View is Component
/// <ul>
///   <li>
///     Component itself is a UIView, no additional view property needed
///   </li>
///   <li>
///     Parent-child relationship is view hierarchy: addChild() automatically calls addSubview()
///   </li>
///   <li>
///     Tree structure managed via Component’s parent/children properties
///   </li>
/// </ul>
SWIFT_CLASS("_TtC6AGenUI9Component")
@interface Component : UIView
/// Backing layer is CAGradientLayer; <code>colors == nil</code> behaves like CALayer.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
/// Removal takes the shadow out of the hierarchy with the body. The shadow
/// view itself stays allocated so a later re-mount can reinsert it without
/// waiting for the next property update.
- (void)removeFromSuperview;
/// Whenever the body lands in a (new) superview, the shadow re-pins itself
/// directly below the body there.
- (void)didMoveToSuperview;
@property (nonatomic, getter=isHidden) BOOL hidden;
@property (nonatomic) CGFloat alpha;
/// Frame setter: notifies <code>onFrameChange</code> and replays shadow/gradient.
/// <code>super.frame =</code> does NOT reliably trigger the <code>bounds</code>/<code>center</code> overrides
/// in Swift — UIKit’s internal <code>setFrame:</code> → <code>setBounds:</code> + <code>setCenter:</code> chain
/// does not dispatch through Swift’s override machinery in all cases.
/// So we replay shadow/gradient directly here.
@property (nonatomic) CGRect frame;
/// Center setter: replays the sibling shadow so it follows position writes
/// that bypass <code>frame</code> (e.g. ButtonComponent.layoutSubviews recentering).
@property (nonatomic) CGPoint center;
/// Bounds setter: replays gradient and sibling shadow on size changes that
/// bypass <code>frame</code> (e.g. direct <code>bounds =</code> writes or CALayer-driven resizes).
@property (nonatomic) CGRect bounds;
/// Trigger UI action to notify SDK of user interaction
/// Component instance is already bound to its identifier, no need to pass it when calling.
/// Sends an empty context, which tells the native layer to use this component’s own
/// <code>action</code> attribute. Kept identical across iOS / Android / HarmonyOS.
- (void)triggerAction;
/// Trigger UI action with a caller-supplied context.
/// Use this when the action to execute is not the component’s own top-level <code>action</code> —
/// e.g. a custom component whose sub-regions carry their own actions (SpanText).
/// The native layer resolves <code>context["action"]</code> as a standard A2UI action definition
/// (<code>{"functionCall": ...}</code> or <code>{"event": ...}</code>); if it is absent or unparsable, the
/// component’s own <code>action</code> attribute is used instead.
/// \param context Context data. Put the action definition under the <code>action</code> key.
///
- (void)triggerActionWithContext:(NSDictionary<NSString *, id> * _Nonnull)context;
/// Sync this component’s UI state to the data model
/// Suitable for UI state changes such as form input, toggle state, etc.
/// \param change State change key-value pair
///
- (void)syncState:(NSDictionary<NSString *, id> * _Nonnull)change;
/// Handle tap event
- (void)handleTap;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class FunctionConfig;
@class FunctionCallContext;
@class FunctionResult;
/// SDK-internal protocol for platform function implementations
/// Bridge layer should adapt external function objects to this protocol
/// before passing them to AGenUI for registration.
SWIFT_PROTOCOL("_TtP6AGenUI8Function_")
@protocol Function
/// Function configuration
@property (nonatomic, readonly, strong) FunctionConfig * _Nonnull functionConfig;
/// Execute the function synchronously
/// \param context Context information containing instanceId and surfaceId
///
/// \param params JSON string containing the function parameters
///
///
/// returns:
/// Execution result with success/failure status and return value
- (FunctionResult * _Nonnull)executeWithContext:(FunctionCallContext * _Nonnull)context params:(NSString * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
@end

/// Context information for a function call
/// Provides the instance and surface context in which the function call is invoked.
SWIFT_CLASS("_TtC6AGenUI19FunctionCallContext")
@interface FunctionCallContext : NSObject
/// Instance unique identifier
@property (nonatomic, readonly) NSInteger instanceId;
/// Surface unique identifier
@property (nonatomic, readonly, copy) NSString * _Nonnull surfaceId;
- (nonnull instancetype)initWithInstanceId:(NSInteger)instanceId surfaceId:(NSString * _Nonnull)surfaceId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK-internal function configuration
SWIFT_CLASS("_TtC6AGenUI14FunctionConfig")
@interface FunctionConfig : NSObject
/// Function name (unique identifier for registration)
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name OBJC_DESIGNATED_INITIALIZER;
/// Serialize config to JSON string for engine registration
- (NSString * _Nonnull)toJSON SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK-internal function execution result
SWIFT_CLASS("_TtC6AGenUI14FunctionResult")
@interface FunctionResult : NSObject
/// Whether the function call succeeded
@property (nonatomic, readonly) BOOL result;
/// Additional data returned by the function call
@property (nonatomic, readonly, copy) NSString * _Nonnull value;
- (nonnull instancetype)initWithResult:(BOOL)result value:(NSString * _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
/// Create a success result
+ (FunctionResult * _Nonnull)successWithValue:(NSString * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
/// Create a failure result
+ (FunctionResult * _Nonnull)failureWithValue:(NSString * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIImage;
/// Pluggable image loader protocol
/// Implement this protocol and register via <code>AGenUI.registerImageLoader(_:)</code> to globally replace image loading logic.
/// Usage example:
/// \code
/// // Use default loader (no configuration needed)
///
/// // Replace with custom loader
/// AGenUI.registerImageLoader(MyKingfisherLoader())
///
/// \endcode
SWIFT_PROTOCOL("_TtP6AGenUI11ImageLoader_")
@protocol ImageLoader
/// Load image
/// \param url Image URL
///
/// \param options Load options (keys use constants from ImageLoadOptionsKey)
///
/// \param completion Completion callback (main thread), parameters are (image, isFromCache, error)
///
///
/// returns:
/// Task identifier, can be used to cancel the task
- (NSString * _Nonnull)loadImageFrom:(NSURL * _Nonnull)url options:(NSDictionary<NSString *, id> * _Nullable)options completion:(void (^ _Nonnull)(UIImage * _Nullable, BOOL, NSError * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
/// Cancel loading task with specified task identifier
/// \param taskId Task identifier to cancel (returned by loadImage)
///
- (void)cancelFor:(NSString * _Nonnull)taskId;
/// Clear memory cache
- (void)clearMemory;
/// Clear disk cache
- (void)clearDisk;
@end

/// Image loader global configuration
SWIFT_CLASS("_TtC6AGenUI24ImageLoaderConfiguration")
@interface ImageLoaderConfiguration : NSObject
/// Singleton
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ImageLoaderConfiguration * _Nonnull shared;)
+ (ImageLoaderConfiguration * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Current image loader
/// <ul>
///   <li>
///     Replace this property to take effect globally
///   </li>
///   <li>
///     Default uses DefaultImageLoader (based on URLSession + memory cache)
///   </li>
/// </ul>
@property (nonatomic, strong) id <ImageLoader> _Nonnull loader;
/// Private initialization
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// AGenUI SDK Logger
/// Provides unified log output interface with log switch control and level filtering
SWIFT_CLASS("_TtC6AGenUI6Logger")
@interface Logger : NSObject
/// Singleton instance
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Logger * _Nonnull shared;)
+ (Logger * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Whether log output is enabled
/// Default is enabled, aligned with Android/Harmony.
/// When no <code>delegate</code> is set, logs fall back to NSLog so the SDK is never silent by default.
@property (nonatomic) BOOL isEnabled;
/// Minimum log level
/// Only logs with level greater than or equal to this will be output
@property (nonatomic) enum Level minimumLevel;
/// Whether to show file name and line number
@property (nonatomic) BOOL showFileInfo;
/// Logger delegate for receiving log events
@property (nonatomic, weak) id <LoggerDelegate> _Nullable delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Output log
/// \param message Log message
///
/// \param level Log level
///
/// \param file File name (auto captured)
///
/// \param function Function name (auto captured)
///
/// \param line Line number (auto captured)
///
- (void)log:(NSString * _Nonnull)message level:(enum Level)level file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
@end

/// Log level
typedef SWIFT_ENUM(NSInteger, Level, open) {
  LevelDebug = 0,
  LevelInfo = 1,
  LevelWarning = 2,
  LevelError = 3,
  LevelFatal = 4,
  LevelPerformance = 5,
};

@interface Logger (SWIFT_EXTENSION(AGenUI))
/// Output debug log
- (void)debug:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
/// Output info log
- (void)info:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
/// Output warning log
- (void)warning:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
/// Output error log
- (void)error:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
/// Output fatal log
- (void)fatal:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
/// Output performance log
- (void)performance:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
/// Output performance log with an explicit event tag.
/// Mirrors the C++ <code>AGENUI_PERFORMANCE_LOG(tag, fmt, ...)</code> and the Android
/// <code>AGenUILogger.perf(eventTag, message)</code> conventions: <code>eventTag</code> is the
/// performance event name (e.g. “components_applied”) and is delivered as
/// the <code>tag</code> parameter to <code>LoggerDelegate.onLog</code>, bypassing the file-name
/// derivation used by <code>performance(_ message:)</code>.
/// \param eventTag Performance event name (forwarded as <code>tag</code> to the delegate).
///
/// \param message Contextual information (e.g. surfaceId).
///
- (void)performance:(NSString * _Nonnull)eventTag message:(NSString * _Nonnull)message file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
@end

/// Logger delegate protocol for receiving log output events
/// Interface design is consistent with C++ ILogObserver
SWIFT_PROTOCOL("_TtP6AGenUI14LoggerDelegate_")
@protocol LoggerDelegate
/// Log output callback
/// \param level Log level
///
/// \param tag Log tag (typically filename)
///
/// \param func Function name
///
/// \param line Line number
///
/// \param message Log message
///
- (void)onLogWithLevel:(enum Level)level tag:(NSString * _Nonnull)tag func:(NSString * _Nonnull)func line:(NSInteger)line message:(NSString * _Nonnull)message;
@end

/// Surface - Independent UI canvas
/// Manages component tree, where each Component is a UIView subclass.
/// The root component serves as the Surface’s view.
SWIFT_CLASS("_TtC6AGenUI7Surface")
@interface Surface : NSObject
/// Surface unique identifier
@property (nonatomic, readonly, copy) NSString * _Nonnull surfaceId;
/// Surface container view
/// Root component will be added as a subview of this view
@property (nonatomic, readonly, strong) UIView * _Nonnull view;
/// Layout change callback
@property (nonatomic, copy) void (^ _Nullable onLayoutChanged)(void);
/// Whether component appear animations are enabled for this surface
@property (nonatomic) BOOL animationEnabled;
/// Original raw protocol content (the full JSON string that was parsed to create this surface)
@property (nonatomic, copy) NSString * _Nonnull rawProtocolContent;
/// Initialize Surface
/// \param surfaceId Surface ID
///
- (nonnull instancetype)initWithSurfaceId:(NSString * _Nonnull)surfaceId OBJC_DESIGNATED_INITIALIZER;
/// Update Surface size constraints
/// \param width New width constraint
///
/// \param height New height constraint
///
- (void)updateSizeWithWidth:(CGFloat)width height:(CGFloat)height;
/// Start blank-check on this Surface.
/// Calling this method <em>immediately</em> schedules a single delayed detection.
/// After <code>checkDelayMs</code> elapses, the SDK counts current valid components on
/// this Surface and emits the result via
/// <code>SurfaceManagerListener.onBlankCheckResult(_:isBlank:componentCount:)</code>.
/// Calling again before the previous detection fires will cancel the previous
/// schedule and start a new one with the latest parameters.
/// \param checkDelayMs Delay (in ms) before detection runs
///
/// \param validComponentCount Threshold; if actual valid component count is lower, treated as blank
///
- (void)startBlankCheckWithCheckDelayMs:(NSInteger)checkDelayMs validComponentCount:(NSInteger)validComponentCount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol SurfaceManagerListener;
/// AGenUI Surface Manager
/// Manages Surface creation, binding, and destruction
/// Also serves as the main SDK entry point
SWIFT_CLASS("_TtC6AGenUI14SurfaceManager")
@interface SurfaceManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Add Surface lifecycle listener
/// \param listener Object implementing SurfaceManagerListener protocol
///
- (void)addListener:(id <SurfaceManagerListener> _Nonnull)listener;
/// Remove Surface lifecycle listener
/// \param listener Listener object to remove
///
- (void)removeListener:(id <SurfaceManagerListener> _Nonnull)listener;
/// Remove all listeners
- (void)removeAllListeners;
/// Returns the native instance id assigned by the engine on creation.
- (NSInteger)getInstanceId SWIFT_WARN_UNUSED_RESULT;
/// Start a new streaming data session
/// Clears the buffer and resets parsing state. Should be called before each streaming session.
- (void)beginTextStream;
/// End the streaming data session
/// Resets parsing state. Should be called after SSE stream closes, HTTP response ends, user aborts, or network disconnects.
- (void)endTextStream;
/// Receive text chunk from external source
/// Receives JSON data for processing. This is the primary method for sending
/// component updates, data model changes, and other instructions to the rendering engine.
/// Usage example:
/// \code
/// let jsonData = """
/// {
///   "version": "v0.9",
///   "updateComponents": {
///     "surfaceId": "main",
///     "components": [...]
///   }
/// }
/// """
/// surfaceManager.receiveTextChunk(jsonData)
///
/// \endcode\param dataString JSON string containing the data to process
///
- (void)receiveTextChunk:(NSString * _Nonnull)dataString;
/// Re-evaluate every component’s attributes and styles across all surfaces managed by
/// this SurfaceManager, then emit field-level diffs to the native renderer for any value
/// that actually changed.
/// Call this when host-owned external state has changed in ways the SDK cannot observe
/// (theme, locale, orientation, etc.) and registered FunctionCalls that read from that
/// state need to be re-run. Action handlers are not in scope.
- (void)invalidateFunctionCallValues;
@end

/// Surface Manager Listener Protocol
/// /// Implement this protocol to receive Surface lifecycle events
SWIFT_PROTOCOL("_TtP6AGenUI22SurfaceManagerListener_")
@protocol SurfaceManagerListener
@optional
/// Surface created callback
/// Called when a Surface has been created
/// \param surface The created Surface object
///
- (void)onCreateSurface:(Surface * _Nonnull)surface;
/// Surface deleted callback
/// Called when a Surface has been deleted
/// \param surfaceId The ID of the deleted Surface
///
- (void)onDeleteSurface:(Surface * _Nonnull)surface;
/// Action event routed callback
/// Called when C++ routes an action event back after processing
/// \param event Action event context JSON string
///
- (void)onReceiveActionEvent:(NSString * _Nonnull)event;
/// Root component update callback
/// Called when the root component’s properties are updated
/// \param surface The Surface whose root component was updated
///
/// \param props The new properties applied to the root component
///
- (void)onRootComponentUpdate:(Surface * _Nonnull)surface props:(NSDictionary<NSString *, id> * _Nonnull)props;
/// SDK error callback
/// \param surface The Surface associated with the error, nil if not associated with a specific Surface
///
/// \param code Error code
///
/// \param message Error description
///
- (void)onError:(Surface * _Nullable)surface code:(NSInteger)code message:(NSString * _Nonnull)message;
/// Blank check result callback
/// Triggered only after <code>Surface.startBlankCheck(checkDelayMs:validComponentCount:)</code> is called.
/// \param surface The detected Surface
///
/// \param isBlank true means determined as blank
///
/// \param componentCount Component-tree size at detection time. Zero means chunks
/// arrived but nothing was built; non-zero on a blank result means the
/// opposite — components exist, too few of them measured non-empty.
///
- (void)onBlankCheckResult:(Surface * _Nonnull)surface isBlank:(BOOL)isBlank componentCount:(NSInteger)componentCount;
/// Synchronously return the current size (in points) of the surface identified by <code>surfaceId</code>.
/// important:
/// This method may be invoked <em>synchronously on a non-main engine worker
/// thread</em>. Implementers must ensure the returned value can be produced in a
/// thread-safe manner and must not perform blocking work on the main thread from here.
/// If multiple listeners are registered, the first listener that returns a positive
/// size wins; others are not consulted.
/// \param surfaceId Surface identifier assigned by the engine.
///
///
/// returns:
/// Current surface size in points (pt). Return <code>.zero</code> if not measurable yet.
- (CGSize)surfaceSizeFor:(NSString * _Nonnull)surfaceId SWIFT_WARN_UNUSED_RESULT;
/// Component appeared callback
/// Called when a child component enters the visible area (e.g., cell bound in List).
/// \param surface The Surface instance
///
/// \param parentComponentId The container component ID that detected the appearance
///
/// \param parentType Container type identifier (“List” / “Carousel” etc.)
///
/// \param properties The appeared child’s full properties dictionary
///
- (void)onComponentAppeared:(Surface * _Nonnull)surface parentComponentId:(NSString * _Nonnull)parentComponentId parentType:(NSString * _Nonnull)parentType properties:(NSDictionary<NSString *, id> * _Nonnull)properties;
@end

/// Tabs component implementation (compliant with A2UI v0.9 protocol)
/// Supported properties:
/// <ul>
///   <li>
///     tabs: Tab array, each with title (String) and child (String component reference) (Array)
///   </li>
/// </ul>
/// Design notes:
/// <ul>
///   <li>
///     Uses InnerTabsView to manage TabBar and content area
///   </li>
///   <li>
///     Custom Tab buttons with animated indicator
///   </li>
///   <li>
///     Content components are added via addChild and shown/hidden based on selected tab
///   </li>
/// </ul>
SWIFT_CLASS("_TtC6AGenUI13TabsComponent")
@interface TabsComponent : Component
/// Called when a tab is selected by user interaction.
/// Subclasses (Swift or Objective-C) can override this method to respond to tab switch events.
/// \param index The index of the selected tab
///
- (void)onTabSelectedWithIndex:(NSInteger)index;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
